FROM nginx:stable-alpine

ENV BACKEND_URL=http://backend:8000

COPY nginx/default.conf /etc/nginx/templates/default.conf.template

COPY index.html /usr/share/nginx/html/index.html
COPY css/ /usr/share/nginx/html/css/
COPY js/ /usr/share/nginx/html/js/

ARG APP_VERSION=local
RUN printf '%s' "$APP_VERSION" > /usr/share/nginx/html/version.txt

EXPOSE 80
