sonar.projectKey=miguet22_TPI1_DEVOPS
sonar.organization=miguet22

sonar.sources=backend,js
sonar.tests=tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=reports/coverage.xml
sonar.javascript.lcov.reportPaths=reports/lcov.info
sonar.exclusions=nginx/**,css/**,index.html
